module.exports = {
  guidesSidebar: [
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'doc',
        id: 'README',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '.'
        }
      ]
    },
  ],
};
