module.exports = {
    guidesSidebar: [
      {
        type: 'category',
        label: 'Guides',
        link: {
          type: 'doc',
          id: 'index',
        },
        items: [
          {
            type: 'autogenerated',
            dirName: '.'
          }
        ]
      },
    ],
  };
