module.exports = {
  myAutogeneratedSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    {
      type: 'link',
      label: 'Meeting Notes',
      href: 'https://developers.stellar.org/meetings',
    }
  ]
};
