module.exports = {
  mySidebar: [
    {
      type: 'link',
      label: 'Dashboard',
      href: '/dashboard',
    },
    {
      type: "autogenerated",
      dirName: ".", // generate sidebar from the docs folder (or versioned_docs/<version>)
    },
  ],
};
