module.exports = {
  myAutogeneratedSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    {
      type: 'link',
      label: 'Meeting Notes (Blog Version)',
      href: '/meetings',
    }
  ]
};
