module.exports = {
  rpcSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Introduction',
        description: 'A public discussion about the design of Soroban RPC',
        slug: '/',
      },
      items: [
        {
          type: "autogenerated",
          dirName: ".",
        },
      ],
    },
    {
      type: 'category',
      label: 'RPC Methods',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'RPC Methods',
        slug: 'methods',
      },
      items: [
        {
          type: 'link',
          label: 'getEvents',
          href: '/rpc/methods/getEvents',
        },
        {
          type: 'link',
          label: 'getHealth',
          href: '/rpc/methods/getHealth',
        },
        {
          type: 'link',
          label: 'getLatestLedger',
          href: '/rpc/methods/getLatestLedger',
        },
        {
          type: 'link',
          label: 'getLedgerEntries',
          href: '/rpc/methods/getLedgerEntries',
        },
        {
          type: 'link',
          label: 'getNetwork',
          href: '/rpc/methods/getNetwork',
        },
        {
          type: 'link',
          label: 'getTransaction',
          href: '/rpc/methods/getTransaction',
        },
        {
          type: 'link',
          label: 'sendTransaction',
          href: '/rpc/methods/sendTransaction',
        },
        {
          type: 'link',
          label: 'simulateTransaction',
          href: '/rpc/methods/simulateTransaction',
        },
      ],
    },
  ],
}
