name: Format MDX and Lint

on:
  pull_request:
    branches:    
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout App Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Start SSH Agent
        run: |
          eval $(ssh-agent -s)

      - name: Setup SSH Key
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh-add private_key
          rm -f private_key

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "Host github.com" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Install App Dependencies
        run: yarn --prefer-offline

      - name: Check MDX
        run: yarn check:mdx

      - name: Build app
        run: yarn build
