name: Format MDX and Lint

on:
  pull_request:
    branches:    
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout App Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install App Dependencies
        run: npm install --prefer-offline

      - name: Check MDX
        run: npm run check:mdx

      - name: Build app
        run: npm run build